# Site settings
name: TWRP Builder
title: TWRP Builder
description: "Jekyll produced devices list"
baseurl: ""
author: berkantkz

collections:
        devices:
                output: true

# Build settings
markdown: kramdown
permalinks: pretty
